# Generated by Django 3.1.7 on 2021-04-10 17:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название статьи')),
                ('platform', multiselectfield.db.fields.MultiSelectField(choices=[('PC', 'PC'), ('Mac', 'Mac'), ('linux', 'linux'), ('Nintendo switch', 'Nintendo switch'), ('PSP', 'PSP'), ('Playstation', 'Playstation'), ('XBOX', 'XBOX'), ('VR', 'VR'), ('Android', 'Android'), ('ios', 'ios')], max_length=50, verbose_name='Платформа')),
                ('genre1', multiselectfield.db.fields.MultiSelectField(choices=[('action', 'action'), ('adventure', 'adventure'), ('simulator', 'simulator'), ('strategy', 'strategy'), ('RPG', 'RPG'), ('puzzle', 'puzzle')], max_length=20, verbose_name='Жанр')),
                ('creators', models.CharField(max_length=50, verbose_name='Разработчик')),
                ('publisher', models.CharField(blank=True, max_length=100, verbose_name='Издатель')),
                ('gm_photo', models.ImageField(upload_to='photos/%y/%m/%d/', verbose_name='Лого игры')),
                ('release_date', models.DateField(verbose_name='Дата релиза')),
                ('text', models.TextField(default='', verbose_name='Обзор на игру')),
                ('steam_url', models.CharField(default='', max_length=100, verbose_name='Ссылка на игру в стиме')),
                ('metascore_url', models.CharField(default='', max_length=100, verbose_name='Ссылка на оценку в метакритике')),
                ('trailer_youtube_url', models.CharField(default='', max_length=200, verbose_name='Ссылка на трейлер в ютубе')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата статьи')),
                ('oform', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Оформление')),
                ('mech', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Механика')),
                ('plot', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Сюжет')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Cтатьи',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_author', models.CharField(max_length=50, verbose_name='Комментатор')),
                ('com_text', models.CharField(max_length=300, verbose_name='Комментарий')),
                ('com_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newes.news')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Коментарии',
            },
        ),
    ]
