# Generated by Django 3.1.7 on 2021-04-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='text2',
            field=models.TextField(blank=True, default='', verbose_name='Обзор на игру2'),
        ),
    ]
